In [ ]:

import numpy as np

# Create a 1D array containing numbers from 1 to 10
arr = np.arange(1, 11)

print("Array:", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Sum of elements:", np.sum(arr))
print("Mean of elements:", np.mean(arr))
print(f"Maximum value: {np.max(arr)}, Minimum value: {np.min(arr)}")

Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Data type: int64
Sum of elements: 55
Mean of elements: 5.5
Maximum value: 10, Minimum value: 1


In [ ]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("1. Matrix Addition:\n", A + B)
print("\n2. Matrix Subtraction:\n", A - B)
print("\n3. Element-wise Multiplication:\n", A * B)
print("\n4. Matrix Multiplication:\n", np.dot(A, B)) # Or use A @ B

1. Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

2. Matrix Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

3. Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

4. Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
import numpy as np

marks = np.array([
    [85, 90, 88, 92],
    [70, 65, 72, 68],
    [95, 91, 93, 96],
    [60, 75, 70, 80],
    [88, 84, 86, 90]
])

# 1. Average marks of each student (mean across columns for each row)
student_averages = np.mean(marks, axis=1)
print("Average marks of each student:", student_averages)

# 2. Average marks of each subject (mean across rows for each column)
subject_averages = np.mean(marks, axis=0)
print("Average marks of each subject:", subject_averages)

# 3. Highest and lowest marks
print(f"Highest marks: {np.max(marks)}, Lowest marks: {np.min(marks)}")

# 4. Student having the highest total marks
total_marks = np.sum(marks, axis=1)
best_student_index = np.argmax(total_marks)
print(f"Student having the highest total marks is Student {best_student_index + 1} with {total_marks[best_student_index]} marks.")

Average marks of each student: [88.75 68.75 93.75 71.25 87.  ]
Average marks of each subject: [79.6 81.  81.8 85.2]
Highest marks: 96, Lowest marks: 60
Student having the highest total marks is Student 3 with 375 marks.


In [ ]:

import numpy as np

image = np.array([
    [100, 120, 130],
    [150, 180, 200],
    [50,  80,  100]
])

# 1. Normalize pixel values (divide by 255)
normalized_image = image / 255.0
print("Normalized Image:\n", normalized_image)

# 2. Increase brightness by 30
brightened_image = image + 30

# 3. Clip values above 255
clipped_image = np.clip(brightened_image, a_min=None, a_max=255)
print("\nBrightened and Clipped Image:\n", clipped_image)

# 4. Calculate average pixel intensity (using original image)
average_intensity = np.mean(image)
print(f"\nAverage pixel intensity: {average_intensity:.2f}")

Normalized Image:
 [[0.39215686 0.47058824 0.50980392]
 [0.58823529 0.70588235 0.78431373]
 [0.19607843 0.31372549 0.39215686]]

Brightened and Clipped Image:
 [[130 150 160]
 [180 210 230]
 [ 80 110 130]]

Average pixel intensity: 123.33


In [ ]:

import numpy as np

sales = np.array([
    [120, 130, 140, 150, 160, 170],
    [100, 110, 120, 130, 140, 150],
    [150, 145, 160, 170, 180, 190],
    [90,  100, 110, 120, 130, 140]
])

# 1. Total sales of each product
total_sales_per_product = np.sum(sales, axis=1)
print("Total sales of each product:", total_sales_per_product)

# 2. Average monthly sales of each product
avg_sales_per_product = np.mean(sales, axis=1)
print("Average monthly sales of each product:", avg_sales_per_product)

# 3. Best-selling product
best_product_index = np.argmax(total_sales_per_product)
print(f"Best-selling product is Product {best_product_index + 1}")

# 4. Month with the highest overall sales
total_sales_per_month = np.sum(sales, axis=0)
best_month_index = np.argmax(total_sales_per_month)
print(f"Month with the highest overall sales is Month {best_month_index + 1}")

# 5. Standard deviation of sales for each product
std_dev_per_product = np.std(sales, axis=1)
print("Standard deviation of sales for each product:", std_dev_per_product)

Total sales of each product: [870 750 995 690]
Average monthly sales of each product: [145.         125.         165.83333333 115.        ]
Best-selling product is Product 3
Month with the highest overall sales is Month 6
Standard deviation of sales for each product: [17.07825128 17.07825128 15.92081098 17.07825128]
